import cron from 'node-cron';
import SalarySlip from '../models/SalarySlip.js';
import SalaryCache from '../models/SalaryCache.js';
import { calculateSalaryForPeriod } from '../services/salary.service.js';


const runningJobs = new Set();

function getIdempotencyKey(year, month, jobType) {
  return `salary:${year}:${month}:${jobType}`;
}

async function generateDraftSlips(year, month, trigger = 'cron') {
  const key = getIdempotencyKey(year, month, 'draft');
  if (runningJobs.has(key)) {
    console.log(`[Payroll] Job ${key} already running — skipping`);
    return;
  }

  runningJobs.add(key);
  const startedAt = Date.now();
  console.log(`[Payroll] ${trigger} — generating draft slips for ${month}/${year}`);

  try {
    const { data: salaryData } = await calculateSalaryForPeriod({ month, year, page: 1, limit: 10000 });
    if (!salaryData || salaryData.length === 0) {
      console.log(`[Payroll] No salary data for ${month}/${year}`);
      return;
    }

    const userIds = salaryData.map(s => s.userId);
    const existingSlips = await SalarySlip.find({
      user: { $in: userIds },
      month,
      year,
    }).lean();

    const existingByUser = {};
    existingSlips.forEach(s => { existingByUser[s.user.toString()] = s; });

    const bulkOps = [];
    let skipped = 0;

    for (const salary of salaryData) {
      const uid = salary.userId.toString();
      const existing = existingByUser[uid];

      // Never touch locked or paid slips
      if (existing && (existing.locked || existing.paymentStatus === 'paid')) {
        skipped++;
        continue;
      }

      const slipData = {
        user: salary.userId,
        month,
        year,
        employeeDetails: {
          name: salary.name,
          username: salary.username,
          employeeId: salary.employeeId,
          role: salary.role,
          department: salary.department,
          jobTitle: salary.jobTitle || '',
        },
        salaryConfig: {
          ctcAmount: salary.ctcAmount,
          salaryType: salary.salaryType,
          perDayTravelAllowance: salary.perDayTravelAllowance || 0,
          railwayPassAmount: salary.railwayPassAmount || 0,
          standardDailyHours: salary.standardDailyHours || 9,
          overtimeRateMultiplier: salary.overtimeRateMultiplier || 1.0,
          otherAmount: salary.otherAmount || 0,
          otherAmountType: salary.otherAmountType || 'earning',
        },
        attendance: salary.attendance,
        grossSalary: salary.grossSalary,
        perDaySalary: salary.perDaySalary,
        perHourRate: salary.perHourRate || 0,
        payableDays: salary.payableDays,
        deductions: salary.deductions,
        reimbursements: salary.reimbursements || { total: 0, count: 0 },
        travel: salary.travel || { perDayAllowance: 0, railwayPass: 0, total: 0 },
        overtime: {
          hours: salary.overtime?.hours || 0,
          rate: salary.overtime?.rate || 0,
          multiplier: salary.overtime?.multiplier || 1.0,
          total: salary.overtime?.total || 0,
        },
        otherAmount: salary.otherAmount || 0,
        otherAmountType: salary.otherAmountType || 'earning',
        netSalary: salary.netSalary,
        paymentStatus: 'pending',
        locked: false,
        generatedAt: new Date(),
        notes: `Auto-generated by ${trigger} job`,
      };

      bulkOps.push({
        updateOne: {
          filter: { user: salary.userId, month, year },
          update: { $set: slipData },
          upsert: true,
        },
      });
    }

    if (bulkOps.length > 0) {
      await SalarySlip.bulkWrite(bulkOps);
    }

    // Refresh salary cache so dashboard reads fresh data next time
    await SalaryCache.findOneAndUpdate(
      { month, year },
      { $set: { employees: salaryData, total: salaryData.length, computedAt: new Date() } },
      { upsert: true }
    );

    const duration = Date.now() - startedAt;
    console.log(
      `[Payroll] ${trigger} — done: ${bulkOps.length} upserted, ${skipped} skipped (locked/paid) in ${duration}ms`
    );
  } catch (err) {
    console.error(`[Payroll] ${trigger} job ${key} failed:`, err.message);
  } finally {
    runningJobs.delete(key);
  }
}

async function reconcileOpenSlips(year, month, trigger = 'cron') {
  const key = getIdempotencyKey(year, month, 'reconcile');
  if (runningJobs.has(key)) {
    console.log(`[Payroll] Reconcile job ${key} already running — skipping`);
    return;
  }

  runningJobs.add(key);
  console.log(`[Payroll] ${trigger} — reconciling open slips for ${month}/${year}`);

  try {
    // Only recalculate for unlocked, non-paid slips
    const openSlips = await SalarySlip.find({
      month,
      year,
      locked: false,
      paymentStatus: { $ne: 'paid' },
    }).lean();

    if (openSlips.length === 0) {
      console.log(`[Payroll] No open slips to reconcile for ${month}/${year}`);
      return;
    }

    const { data: salaryData } = await calculateSalaryForPeriod({ month, year, page: 1, limit: 10000 });
    const salaryByUser = {};
    salaryData.forEach(s => { salaryByUser[s.userId.toString()] = s; });

    const bulkOps = [];
    for (const slip of openSlips) {
      const uid = slip.user.toString();
      const salary = salaryByUser[uid];
      if (!salary) continue;

      bulkOps.push({
        updateOne: {
          filter: { _id: slip._id },
          update: {
            $set: {
              attendance: salary.attendance,
              grossSalary: salary.grossSalary,
              perDaySalary: salary.perDaySalary,
              perHourRate: salary.perHourRate || 0,
              payableDays: salary.payableDays,
              deductions: salary.deductions,
              reimbursements: salary.reimbursements || { total: 0, count: 0 },
              travel: salary.travel || { perDayAllowance: 0, railwayPass: 0, total: 0 },
              overtime: {
                hours: salary.overtime?.hours || 0,
                rate: salary.overtime?.rate || 0,
                multiplier: salary.overtime?.multiplier || 1.0,
                total: salary.overtime?.total || 0,
              },
              otherAmount: salary.otherAmount || 0,
              otherAmountType: salary.otherAmountType || 'earning',
              netSalary: salary.netSalary,
              notes: `Reconciled by ${trigger} on ${new Date().toISOString()}`,
            },
          },
        },
      });
    }

    if (bulkOps.length > 0) {
      await SalarySlip.bulkWrite(bulkOps);
    }

    // Update cache with latest reconciled data
    await SalaryCache.findOneAndUpdate(
      { month, year },
      { $set: { employees: salaryData, total: salaryData.length, computedAt: new Date() } },
      { upsert: true }
    );

    console.log(`[Payroll] Reconciled ${bulkOps.length} open slips for ${month}/${year}`);
  } catch (err) {
    console.error(`[Payroll] Reconcile job ${key} failed:`, err.message);
  } finally {
    runningJobs.delete(key);
  }
}

export function startPayrollScheduler() {
  // 14.4 — Monthly job: 02:00 AM IST on 1st of every month → generate previous month draft slips
  // IST = UTC+5:30 → 02:00 IST = 20:30 UTC previous day → cron in UTC: "30 20 L * *" (last day)
  // Simpler: run at 02:30 IST on the 1st = 21:00 UTC on the last day of previous month
  // Using 'Asia/Kolkata' timezone support (node-cron v3+)
  cron.schedule('0 2 1 * *', async () => {
    const now = new Date(new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
    // Generate for previous month
    const prevMonth = now.getMonth() === 0 ? 12 : now.getMonth(); // getMonth() is 0-indexed, now we're on 1st so prev month
    const prevYear = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();
    await generateDraftSlips(prevYear, prevMonth, 'monthly-cron');
  }, { timezone: 'Asia/Kolkata' });

  // 14.4 — Daily job: 02:30 AM IST → reconcile current open payroll period
  cron.schedule('30 2 * * *', async () => {
    const now = new Date(new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
    const month = now.getMonth() + 1;
    const year = now.getFullYear();
    await reconcileOpenSlips(year, month, 'daily-cron');
  }, { timezone: 'Asia/Kolkata' });

  console.log('[Payroll] Scheduler started — monthly (1st 02:00 IST) + daily (02:30 IST)');
}

// Export for manual triggering from admin API
export { generateDraftSlips, reconcileOpenSlips };
